//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace activitytool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("activitytool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 http://apps.game.qq.com/ams/ame/ame.php?ameVersion=0.3&amp;sServiceType=tgclub&amp;iActivityId={actid}&amp;sServiceDepartment=xinyue&amp;set_info=xinyue&amp;sSDID={sSDID}&amp;isXhrPost=true 的本地化字符串。
        /// </summary>
        internal static string ameURL {
            get {
                return ResourceManager.GetString("ameURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sCdKey={CDK}&amp;iUin={QQ}&amp;sVerifyCode={Code}&amp;isVerifyCode=1&amp;iVerifyId=21000104&amp;sArea={area}&amp;sPartition=&amp;sRoleId={roleid}&amp;sServiceType=dnf&amp;sRoleName={u2rolename}&amp;md5str={md5str}&amp;ams_checkparam={u2checkparam}&amp;checkparam={u2checkparam}&amp;iActivityId=10502&amp;iFlowId=87571&amp;g_tk={ametk}&amp;e_code=0&amp;g_code=0&amp;eas_url=http%253A%252F%252Fdnf.qq.com%252Fgift.shtml&amp;eas_refer=http%253A%252F%252Fdnf.qq.com%252Fcomm-htdocs%252Flogin%252FloginSuccess.html&amp;xhr=1&amp;sServiceDepartment=x6m5&amp;xhrPostKey=xhr_1503650727860 的本地化字符串。
        /// </summary>
        internal static string DNFCDKPost {
            get {
                return ResourceManager.GetString("DNFCDKPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://x6m5.ams.game.qq.com/ams/ame/ame.php?ameVersion=0.3&amp;sServiceType=dnf&amp;iActivityId=10502&amp;sServiceDepartment=x6m5&amp;sSDID=undefined 的本地化字符串。
        /// </summary>
        internal static string DNFCDKURL {
            get {
                return ResourceManager.GetString("DNFCDKURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;yzm_id&quot;
        ///
        ///[验证码id]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///+8z1lB53mIowlCmwh
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getErrorCode {
            get {
                return ResourceManager.GetString("getErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;yzm_id&quot;
        ///
        ///[打码Id]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///XTKH8Uyb9f6IfTKH4
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getResultParameter {
            get {
                return ResourceManager.GetString("getResultParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;upload&quot;; filename=&quot;ab497e47984c60d9bbc93d5b920e036c.jpg&quot;
        ///Content-Type: image/gif 的本地化字符串。
        /// </summary>
        internal static string getUpload1 {
            get {
                return ResourceManager.GetString("getUpload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;yzmtype_mark&quot;
        ///
        ///[yzmtype]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;yzm_minlen&quot;
        ///
        ///[yzm_minlen]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;yzm_maxlen&quot;
        ///
        ///[yzm_maxlen]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string getUpload2 {
            get {
                return ResourceManager.GetString("getUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///kldHJgXoLnMa3gXUF
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getUser {
            get {
                return ResourceManager.GetString("getUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///kldHJgXoLnMa3gXUF
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getUserCode {
            get {
                return ResourceManager.GetString("getUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_email&quot;
        ///
        ///
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_qq&quot;
        ///
        ///
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_phone&quot;
        ///
        ///
        ///---- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Reglz {
            get {
                return ResourceManager.GetString("Reglz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iActivityId={actid}&amp;iFlowId={flowid}&amp;g_tk={ametk}&amp;e_code=0&amp;g_code=0&amp;eas_url=http%253A%252F%252Fxinyue.qq.com%252Fact%252Fpc%252Fa20160623dnfryzc%252F&amp;eas_refer=&amp;xhr=1&amp;sServiceDepartment=xinyue&amp;sServiceType=dnf&amp;sArea={area}&amp;sPartition={area}&amp;sRoleId={roleid}&amp;sAreaName={u1areaname}&amp;sRoleName={u1rolename}&amp;md5str={md5str}&amp;ams_checkparam={checkparam}&amp;checkparam={checkparam}&amp;xhrPostKey=xhr_1503995858746 的本地化字符串。
        /// </summary>
        internal static string ryzcbindPostdata {
            get {
                return ResourceManager.GetString("ryzcbindPostdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iActivityId={actid}&amp;iFlowId={flowid}&amp;g_tk={ametk}&amp;e_code=0&amp;g_code=0&amp;eas_url=http%253A%252F%252Fxinyue.qq.com%252Fact%252Fpc%252Fa20160623dnfryzc%252F&amp;eas_refer=&amp;xhr=1&amp;sServiceDepartment=xinyue&amp;sServiceType=tgclub&amp;xhrPostKey=xhr_1503895011297 的本地化字符串。
        /// </summary>
        internal static string ryzcPostdata {
            get {
                return ResourceManager.GetString("ryzcPostdata", resourceCulture);
            }
        }
    }
}
